enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "LisoUseInAIKyrios/revanced-patches"
integrations-source = "LisoUseInAIKyrios/revanced-integrations"
rv-brand = "LisoUseInAIKyrios ReVanced"
build-mode = "module"

